# Generated by Django 2.1.1 on 2018-10-11 04:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('article', markdownx.models.MarkdownxField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 10, 11, 4, 50, 36, 213936, tzinfo=utc))),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2018, 10, 11, 4, 50, 36, 213962, tzinfo=utc), null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
